[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sub-project-1-for-ssc-scanning"
version = "0.1.0"
description = "Test project for Syft and Trivy SBOM generation"
requires-python = "==3.11.*"
dependencies = [
    "numpy==1.23.5",
    "pandas==2.1.1",
    "scikit-learn==1.3.1",
    "tensorflow==2.12.0",        # CVE-2023-25658: Buffer overflow in model parsing (Critical)
    "pillow==9.0.0",             # CVE-2022-22817: Arbitrary Code Execution (High)
    #"pypdf==3.8.0",              # CVE-2023-36464: Infinite Loop DoS (Medium)
    #"onnx==1.14.0",              # CVE-2024-5187: Critical Remote Code Execution (Critical)
    #"torch==2.0.0",              # CVE-2025-32434: Remote Code Execution (Critical)
]