name: Syft SBOM & Trivy Security Pipeline

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  security-scan:
    runs-on: ubuntu-24.04
    permissions:
      contents: read          # Kód letöltéséhez kell
      security-events: write  # A GitHub Security fül írásához (SARIF feltöltés)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Syft telepítése és SBOM generálása
      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Generate SBOM for Repository with Syft
        run: syft dir:. -o cyclonedx-json > repo-sbom.json

      # 2. Trivy futtatása a Syft SBOM-on (Action segítségével)
      - name: Scan Syft SBOM with Trivy
        uses: aquasecurity/trivy-action@0.35.0
        with:
          scan-type: 'sbom'
          scan-ref: 'repo-sbom.json'  # Ide adjuk át a Syft SBOM fájlt!
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true

      # 3. SARIF eredmények feltöltése a GitHub Security fülre
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy-results.sarif'

      # 4. Az eredeti Syft SBOM lementése artifact-ként
      - name: Upload Syft SBOM as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Syft-SBOM
          path: repo-sbom.json

      - name: Upload SBOM to Dependency-Track
        uses: DependencyTrack/gh-upload-sbom@v3
        with:
          serverHostname: ${{ secrets.DEPENDENCYTRACK_URL }}
          apiKey: ${{ secrets.DEPENDENCYTRACK_APIKEY }}
          projectName: 'Sub-Project-1-for-SSC-Scanning'
          projectVersion: '1'
          bomFilename: "repo-sbom.json"
          autoCreate: false